version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: spring-batch-container
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --skip-character-set-client-handshake
    restart: always
    environment:
      MYSQL_DATABASE: spring-batch-db
      MYSQL_USER: admin
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_PASSWORD: 1234
      volumes: data:/var/lib/mysql
    ports:
      - "3311:3306"

volumes:
  data: