spring:
  profiles:
    include: local
  # spring.batch.job.name을 사용하면 여러 개의 job 중에 특정 job만 실행할 수 있다.
  batch:
    job:
      name: stepNextConditionalJob

---
spring:
  config:
    activate:
      on-profile: local
  datasource:
    hikari:
      jdbc-url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
      username: sa
      password:
      driver-class-name: org.h2.Driver

---
spring:
  config:
    activate:
      on-profile: mysql
  datasource:
    hikari:
      jdbc-url: jdbc:mysql://localhost:3312/spring-batch-db
      username: admin
      password: 1234
      driver-class-name: com.mysql.jdbc.Driver